# Generated by Django 5.0.6 on 2024-07-10 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_remove_event_description_remove_event_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.TextField(default='test', max_length=600),
            preserve_default=False,
        ),
    ]
